alerta/docker-alerta

Dockerfile, docker-compose.yml
Using latest version of Docker Composer which supports version 2.1 compose files means you can use environment variables with default values.
Note that setting the MongoDB environment variable like so `MONGO_URI=mongodb://db:27017/monitoring` means no special handling is required in the `database.py` module in Alerta server for Docker, any more.
=> Switch to Docker compose

.gitignore, Dockerfile, supervisord.conf, uwsgi.ini
Docker is now based on the tutorial at http://docs.alerta.io/en/latest/gettingstarted/tutorial-1-deploy-alerta.html#tutorial-1
=> Replace gunicorn with uwsgi

README.md, docker-entrypoint.sh
**PLUGINS** env variable should not have default value, reject is still a plugin, so if somebody would like to use *vanilla* alerta he would have to add some other plugin. So there is no way right now to have *vanilla* alerta.
Seperate Enabled plugins (**PLUGINS** variable) from Installed Plugins(**INSTALL_PLUGINS**), main reason is pretty simple, if you put another layer above original image (as is mentioned in https://github.com/alerta/docker-alerta#installing-plugins) with installed plugins, you cannot enable them other way than also binding configuration file with plugins, and then it would still try to install them.
This change simplify local plugin development under docker environment.
Enclosing bash variable into curly braces and double quotes:
This is best practice (for example …
=> Split Plugins to Enable and To Install, Remove fefault PLUGINS value, Enclose bash variables into curly brackets and double quote

Dockerfile
Found a working example...
```
ENV APP_ROOT=/opt/app-root
ENV PATH=${APP_ROOT}/bin:${PATH} HOME=${APP_ROOT}
COPY bin/ ${APP_ROOT}/bin/
RUN chmod -R u+x ${APP_ROOT}/bin && \
chgrp -R 0 ${APP_ROOT} && \
chmod -R g=u ${APP_ROOT} /etc/passwd
USER 10001
WORKDIR ${APP_ROOT}
```
https://github.com/RHsyseng/container-rhel-examples/blob/master/starter-arbitrary-uid/Dockerfile.centos7
=> Set files to root group ownership

README.md
When i try to use alerta/alerta-web container image, i found the service expose port is 8080 inside (see Dockerfile), not 80. So i fix the readme file for someone like me to try this alerta-web container.
=> Fix alerta-web container inside port in README

docker-entrypoint.sh
When not config alerta cli config file, execute CLI (docker exec alerta-web alerta query) will output error message like this:
Traceback (most recent call last):
File "/venv/bin/alerta", line 11, in <module>
sys.exit(cli())
File "/venv/lib/python3.6/site-packages/click/core.py", line 722, in __call__
return self.main(*args, **kwargs)
File "/venv/lib/python3.6/site-packages/click/core.py", line 697, in main
rv = self.invoke(ctx)
File "/venv/lib/python3.6/site-packages/click/core.py", line 1066, in invoke
return _process_result(sub_ctx.command.invoke(sub_ctx))
File "/venv/lib/python3.6/site-packages/click/core.py", line 895, in invoke
return ctx.invoke(self.callback, **ctx.params)
File "/venv/lib/python3.6/site-packages/click/core.py", line 535, in invoke
return callback(*args, **kwargs) …
=> Fix alerta client config missing when not create admin user

backend/Dockerfile, backend/docker-entrypoint.sh, backend/uwsgi.ini.template, backend/wsgi.py, frontend/Dockerfile, frontend/alerta-frontend-entrypoint.sh, frontend/config.js.template
Hi,
recently we have deployed alerta in our company and we have a pretty high load, so we have decided to use alerta in HA. Sadly we have found out that alerta runs as `All in One` solution within docker container,
which is a bit inappropriate for docker orchestration such as kubernetes. Kubernetes allows to define liveness / readiness probes which are checking if container is alive / responding to requests. Using standard alerta image led to frontend being inaccessible all the time as the container were getting killed and recreated.
Because of this we splited  the image into two, one for frontend and one for backend. This allows us to have lower number of frontends (in our case 2) and scale only backends dynamically based on currrent load / requirements.
So this proposal is primarily for …
=> Separate images for backend and frontend

Makefile, docker-compose.mongo.yml, docker-compose.postgres.yml, docker-compose.yml, docker-entrypoint.sh, nginx.conf
The web UI will now be served from the same path as the `BASE_URL` minus the `/api`. For example, if `BASE_URL=/alerta/api` then the Alert web UI will be available at `/alerta`.
Fixes #61
=> Apply BASE_URL to web console URL also

contrib/kubernetes/backend/Dockerfile
The .ini references a group that doesn't exist (alerta) - need to add to the dockerfile otherwise it will error out with:
```
+ RUN_ONCE=/app/.run_once
+ '[' '!' -f /app/alertad.conf ']'
+ cat
++ tr -dc 'A-Za-z0-9_!@#$%^&*()-+='
++ head -c 32
+ '[' '!' -f /app/.run_once ']'
+ '[' -n '' ']'
++ cut '-d ' -f1
++ alertad keys
++ head -1
+ API_KEY=
+ '[' -n '' ']'
+ IFS=,
+ touch /app/.run_once
+ envsubst
+ exec uwsgi --ini /app/uwsgi.ini
[uWSGI] getting INI configuration from /app/uwsgi.ini
*** Starting uWSGI 2.0.17.1 (64bit) on [Thu Jul 12 11:40:10 2018] ***
compiled with version: 6.3.0 20170516 on 12 July 2018 10:26:34
os: Linux-4.14.22+ #1 SMP Thu May 10 17:54:42 PDT 2018
nodename: alerta-backend-6879fc85f7-mblsc
machine: x86_64
clock source: unix
pcre jit disabled
detected number of CPU …
```
=> Add Alerta group to the dockerfile

uwsgi.ini
>By default uWSGI allocates a very small buffer (4096 bytes) for the headers of each request. If you start receiving “invalid request block size” in your logs, it could mean you need a bigger buffer. Increase it (up to 65535) with the buffer-size option.
https://uwsgi-docs.readthedocs.io/en/latest/ThingsToKnow.html
Fixes https://github.com/alerta/alerta/issues/636
=> Double the uwsgi request header buffer size

Dockerfile
This adds `python-ldap` to image, so LDAP auth would work.
Tested with on-premises Active Directory.
=> Add support for LDAP auth

Makefile, config.json.template, docker-compose.simple.yml, docker-entrypoint.sh
Second attempt at fixing subpath support. See #131 
To deploy Alerta at a subpath set the `BASE_URL` environment variable:
```
BASE_URL=/alerta2/api
```
... this will deploy the Alerta web UI at `/alerta2/` subpath. 
**Note:** There are still issues with refreshing the browser when at a dynamic route (eg. `/alert/:id`) but that is a separate issue, I think, and not actually related to getting subpaths working.
=> Set web UI subpath from base URL if provided

examples/envoy/api/alertad.conf, examples/envoy/docker-compose.yaml, examples/envoy/proxy/front-proxy.yaml, examples/envoy/webui/.env, examples/envoy/webui/Dockerfile, examples/envoy/webui/config.json, examples/envoy/webui/nginx.conf
To reverse proxy Alerta using Envoy proxy set the following ...
Web `.env` file
-  **must have** `BASE_URL=/non/root/path/`
- **must** build alerta-web new container with site-specific `BASE_URL`
API `alertad.conf` file
- *recommended to set* `BASE_URL` of API endpoint but currently broken eg. `BASE_URL='http://foo.example.com/alerta/api'`
- *recommended to set* `USE_PROXYFIX=True` but not sure it does anything
Steps to run this example...
```
$ cd examples/envoy
$ docker-compose build
$ docker-compose up
```
browse to http://local.alerta.io:8000/alerta/ui
=> Add example envoy proxy setup

contrib/kubernetes/helm/alerta/templates/deployment.yaml
Kubernetes declared the apps/deployment definition starting with 1.16 as stable so the api version `apps/v1beta2` should be replaced  the new api version `apps/v1`.
This PR updates the deployment specification to use the new api version.
=> update deprecated deployment api version from apps/v1beta2 to apps/v1

contrib/kubernetes/helm/alerta/Chart.yaml, contrib/kubernetes/helm/alerta/requirements.yaml, contrib/kubernetes/helm/alerta/values.yaml
This PR will update the helm chart to the current version of alerta (7.5.1) and also updates the postgresql requirement to the current version of 8.6.0
=> update alerta image and postgresql requirement to current versions

contrib/kubernetes/helm/alerta/requirements.yaml
- official chart is depcrecated. Bitnami chart is recommended. Hence dependency is updated
- also K8s 1.16 needs api update: https://kubernetes.io/blog/2019/07/18/api-deprecations-in-1-16/ otherwise I got:
```
unable to recognize "alerta-kustomize": no matches for kind "Deployment" in version "apps/v1beta2"
unable to recognize "alerta-kustomize": no matches for kind "StatefulSet" in version "apps/v1beta2
```
=> Update postgres dependency to bitnami charts

contrib/kubernetes/helm/alerta/templates/deployment.yaml
- I have seem now some occurences where supervisor takes its time to bring up everything cleanly, especially when plugins are installed, etc.
- Therefore in Kubernetes its recommended to delay the start of checking health or readiness probes to give the app more time to come up
- `initialDelaySeconds` of `300` seconds fixes the issue
=> Add probes initial delay cause of startup slowness

contrib/kubernetes/helm/alerta/templates/ingress.yaml
The kind `Ingress` of the API version `extensions/v1beta1` is deprecated.
`warning: extensions/v1beta1/Ingress is deprecated by networking/v1beta1/Ingress and not supported by Kubernetes v1.20+ clusters.`
This PR upgrades the ingress manifest to use the new API version.
=> fix depcreation of extensions/v1beta1/Ingress

Dockerfile
This is a minor fix to make `cd` command in the `alerta` container work, given that when the user is added in the `Dockerfile` it implicitly gets `/home/alerta` ad home directory, which does not exist.
```
▶ docker run -it alerta/alerta-web:8.0.2 bash
Unable to find image 'alerta/alerta-web:8.0.2' locally
8.0.2: Pulling from alerta/alerta-web
Digest: sha256:23f8ddd64e84f77b40a1c5a80977fdd2490bddb0310589836b78c36eb6b98fcc
Status: Downloaded newer image for alerta/alerta-web:8.0.2
Alerta init process complete; ready for start up.
alerta@1aba1124f58d:/$ cd
bash: cd: /home/alerta: No such file or directory
alerta@1aba1124f58d:/$
```
=> Creating home directory for alerta user

contrib/kubernetes/helm/alerta/templates/service.yaml
Hello,
this PR add support for NodePort [1] service type to helm chart.
Example
```yaml
service:
type: NodePort
port: 8080
nodeport: 30080
```
[1] https://kubernetes.io/docs/concepts/services-networking/service/#nodeport
=> Added support for NodePort service type (Helm)

README.md, config/templates/app/supervisord.conf.j2
Set the log level of the `supervisord` daemon. Default is `debug` so that new users of the container aren't confused by nothing being logged. Set to `info` or higher to suppress nginx/flask logging...
```
SUPERVISORD_LOG_LEVEL=info
```
Supercedes #308
=> Add option to control supervisord log level

contrib/kubernetes/helm/alerta/templates/configmap.yaml
Some Alerta config values are typically multiline constructs, e.g. `SEVERITY_MAP` (see [docs](https://docs.alerta.io/configuration.html#severity-settings)). So far, using multiline values breaks the indentation of this ConfigMap.
This change adds indentation to all but the first line, so that multiline values are possible. It does not impact single-line values.
Example use:
```yaml
alertaConfig:
SEVERITY_MAP: |
{
'security': 0,
'critical': 1,
'whatever': 10
}
```
The resulting config is syntactically correct and matches the format used in the docs.
=> Helm chart: handle multiline config values

docker-entrypoint.sh
This is my proposal to fix https://github.com/alerta/docker-alerta/issues/370
=> fix: Add admin:alerts scope to the Housekeeping key if CUSTOMER_VIEWS is enabled

contrib/kubernetes/helm/alerta/Chart.yaml, contrib/kubernetes/helm/alerta/templates/deployment.yaml, contrib/kubernetes/helm/alerta/templates/ingress.yaml, contrib/kubernetes/helm/alerta/values.yaml
Add a Helm variable in chart to specify the class name of the ingress.  
Allow to be compliant with `ingress-nginx` `>=1.0.0`
I took the opportunity to bump the chart version and use application version by default as the tag of the pod image.
=> Add Helm variable for ingress class name.

examples/nginx/webui/Dockerfile
Docker build was failing due to incompatibilities with the referenced node:lts-alpine image, which seems to use node16.
Changed to use node:14-buster image, and removed alpine specific lines (apk add).
=> Update nginx example webui Dockerfile to fix build

config/templates/app/nginx.conf.j2, docker-compose.yml
When dealing with large alerts (>1M) NGINX would return a 413 error. This fixes that by allowing the end user to set the NGINX `client_max_body_size` via the environment variable `NGINX_MAX_BODY_SIZE`. NGINX defaults to 1M which was causing issues with large alerts.
Fixes #441
**Changes**
Include a brief summary of changes...
- added environment variable to nginx.conf.j2
- added sample configuration to docker-compose.yml (commented out by default)
**Checklist**
**Collaboration**
When a user creates a pull request from a fork that they own, the user
generally has the authority to decide if other users can commit to the
pull request's compare branch. If the pull request author wants greater
collaboration, they can grant maintainers of the upstream repository
(that is, anyone …
=> Fix nginx 413 error

docker-entrypoint.sh
I recently upgraded our setup to docker-web:9.0.1 and discovered that my previous commit on the entrypoint broke it and was generating a housekeeping api key with wrong scope (every scope was surrounded by double quotes).
This PR fixes my mistake
**Changes**
Remove the quotes from the scopes that were introduced in https://github.com/alerta/docker-alerta/commit/a584da59f43ac270dc18b5f72c0eb1029cf0e540. 
**Checklist**
**Collaboration**
When a user creates a pull request from a fork that they own, the user
generally has the authority to decide if other users can commit to the
pull request's compare branch. If the pull request author wants greater
collaboration, they can grant maintainers of the upstream repository
(that is, anyone with push access to the upstream repository) …
=> fix: Fix entrypoint housekeeping api key scope format
