config.js.sh
config.js.sh.example

Fix missing comma in config.js.sh and add example

---

README.md
docker-compose.yml

Add docker compose to README

---

Dockerfile
docker-entrypoint.sh

Add alert on stale heartbeats cron job

---

docker-entrypoint.sh

Fix plugin name error on container restart

---

Dockerfile
config/alertad.conf.example
docker-compose.yml
docker-entrypoint.sh
wsgi.py

Update docker config to support release 5.0

---

Dockerfile
docker-compose.yml
docker-entrypoint.sh
nginx.conf
supervisord.conf
uwsgi.ini

Fix issues with user-defined BASE_URL

---

Dockerfile

See https://docs.openshift.com/enterprise/3.0/creating_images/guidelines.html#use-uid

Support arbitrary user Ids for OpenShift v3

---

Dockerfile

```
$ docker exec -ti d6d29f27e084 bash
I have no name!@d6d29f27e084:/$
```

Fix "I have no name"

---

supervisord.conf

See https://github.com/alerta/python-alerta-client/pull/118

Make use of new housekeeping command

---

Dockerfile

Add alerta user to Dockerfile

---

Makefile
README.md
config/alerta.conf.example
docker-compose.simple.yml
docker-compose.yml
docker-entrypoint.sh

Allow client config to be overridden

---

docker-compose.mongo-replica.yml
docker-compose.mongo.yml
docker-compose.postgres.yml
docker-compose.simple.yml
docker-compose.yml

**Example**
```
$ docker-compose -f docker-compose.yml -f docker-compose.postgres.yml pull
$ docker-compose -f docker-compose.yml -f docker-compose.postgres.yml up
```

Bump docker-compose to version 3.1

---

Dockerfile
RUNBOOK.md
config.js.template
config/alertad.conf.example
docker-compose.yml
docker-entrypoint.sh
hooks/build

Adds support for the following environment variables (with defaults) ...
```
GITHUB_URL "https://github.com"
GITLAB_URL "https://gitlab.com"
KEYCLOAK_URL "https://keycloak.example.org"
KEYCLOAK_REALM "master"
PINGFEDERATE_URL "https://pingfederate.example.org"
COLORS {}
SEVERITY {}
AUDIO {}
TRACKING_ID ""
```
Fixes #86

Support all env vars for web UI config.js

---

contrib/kubernetes/helm/alerta/.helmignore
contrib/kubernetes/helm/alerta/Chart.yaml
contrib/kubernetes/helm/alerta/requirements.yaml
contrib/kubernetes/helm/alerta/templates/NOTES.txt
contrib/kubernetes/helm/alerta/templates/_helpers.tpl
contrib/kubernetes/helm/alerta/templates/configmap.yaml
contrib/kubernetes/helm/alerta/templates/deployment.yaml
contrib/kubernetes/helm/alerta/templates/ingress.yaml
contrib/kubernetes/helm/alerta/templates/secrets.yaml
contrib/kubernetes/helm/alerta/templates/service.yaml
contrib/kubernetes/helm/alerta/values.yaml

Signed-off-by: Michal Wasilewski <mwasilewski@gmx.com>

helm chart for kubernetes deployment

---

Dockerfile

Revert default install of python ldap package

---

slash/docker-entrypoint.sh

fix for Heartbeat API Key is invalid #110

---

nginx.conf

Fix page refresh bug for html5 history mode app

---

contrib/kubernetes/helm/alerta/templates/deployment.yaml
contrib/kubernetes/helm/alerta/templates/secrets.yaml
contrib/kubernetes/helm/alerta/values.yaml

- add admin / api key
- fix admin users list

add admin / api key

---

nginx.conf

Adding IPv6 support requires custom build

---

Dockerfile

Update to python 3.7

---

requirements.txt

Add python-ldap

---

requirements.txt

Install pysaml2 by default

---

Dockerfile
README.md
config.json
config.json.template
docker-compose.yml
docker-entrypoint.sh
nginx.conf
requirements.txt
uwsgi.ini

* Fix for container failing to launch if /app is read-only mount #160 
* Fix for subpath hack by removing BASE_URL option #173, #161

Remove support for base-url subpath config option

---

examples/nginx/api/alertad.conf
examples/nginx/docker-compose.yaml
examples/nginx/proxy/nginx.conf
examples/nginx/proxy/proxy.conf
examples/nginx/webui/.env
examples/nginx/webui/Dockerfile
examples/nginx/webui/config.json
examples/nginx/webui/nginx.conf

Add example nginx proxy setup

---

Dockerfile
docker-compose.yml
docker-entrypoint.sh
plugins.txt
requirements.txt

Simplify entrypoint script

---

.github/workflows/docker.yml

Add slack notify to GitHub workflow

---

.github/workflows/docker.yml
.gitignore
Dockerfile

Add xmlsec1 package

---

contrib/kubernetes/helm/alerta/Chart.yaml
contrib/kubernetes/helm/alerta/values.yaml

Lets make sure helm is updated

point to latest alerta-web build

---

contrib/kubernetes/helm/alerta/Chart.yaml
contrib/kubernetes/helm/alerta/templates/deployment.yaml
contrib/kubernetes/helm/alerta/values.yaml

Add secret management in helm charts in order to put certificate for authentication.

add secret management in helm charts

---

Dockerfile

build(docker): upgrade nginx

---

contrib/kubernetes/helm/alerta/templates/deployment.yaml

I've confirmed this does indeed fix the issue.

resolve #270

---

Dockerfile
supervisord.conf

It would be nice to be able to override..

allow to specify housekeeping hours for expired and info alerts

---

config/templates/app/nginx.conf.j2
config/templates/app/uwsgi.ini
tests.sh

Fix nginx settings for forwarding headers

---

docker-entrypoint.sh

#338 
Only generate config files if they don't exist, applies to all config files.

Only generate config files if not supplied.

---

config/templates/app/nginx.conf.j2
examples/alerta/docker-compose.yml

Simply nginx access logging

---

contrib/kubernetes/helm/alerta/templates/configmap.yaml
contrib/kubernetes/helm/alerta/templates/deployment.yaml
contrib/kubernetes/helm/alerta/values.yaml

It should be possible to pass additional configs and environment variables.
**Changes**
- Update helm chart to accept additional configs and environment variables
**Checklist**

Allow to pass additional configs and environment variables

---

Dockerfile

Update the base image to Python 3.9.
Fixes #393
**Changes**
Base image.
**Screenshots**
n/a
**Checklist**
**Collaboration**
When a user creates a pull request from a fork that they own, the user
generally has the authority to decide if other users can commit to the
pull request's compare branch. If the pull request author wants greater
collaboration, they can grant maintainers of the upstream repository
(that is, anyone with push access to the upstream repository) permission
to commit to the pull request's compare branch
See https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork

Bump base image to Python 3.9

---

config/templates/app/nginx.conf.j2

Make this compatible with IPv6.
Fixes no issue (no one found)
**Changes**
- Enable the proxy to listen on IPv6
**Screenshots**
No UI changes
**Checklist**

Add IPv6 compatibility

---

requirements-docker.txt

A clear and concise description of **why** this change is necessary.
Fixes # (issue)
**Changes**
Include a brief summary of changes...
- change 1
- change 2
- change 3
**Screenshots**
If it's a UI change add screenshots to demonstrate changes.
**Checklist**
**Collaboration**
When a user creates a pull request from a fork that they own, the user
generally has the authority to decide if other users can commit to the
pull request's compare branch. If the pull request author wants greater
collaboration, they can grant maintainers of the upstream repository
(that is, anyone with push access to the upstream repository) permission
to commit to the pull request's compare branch
See https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/allowing …

build(deps): bump lxml
